[workspace]
members = [
    "canister/api",
    "canister/impl",
    "client",
    "client/agent_runtime",
    "client/cdk_runtime",
    "integration_tests",
    "utils",
]
resolver = "2"

[workspace.dependencies]
candid = "0.10.3"
ic-agent = "0.32.0"
ic-cdk = "=0.12.0"
ic-cdk-timers = "0.6.0"
ic_principal = "0.1.1"
ic-stable-structures = "0.6.2"
pocket-ic = "2.0.1"
rand = "0.8.5"
rmp-serde = "1.1.2"
serde = "1.0.196"
serde_bytes = "0.11.14"
tokio = "1.36.0"
tokio-util = "0.7.10"
tracing = "0.1.40"

[patch.crates-io]
pocket-ic = { git = "https://github.com/dfinity/ic", rev = "044cfd5147fc97d7e5a214966941b6580c325d72" }
