[workspace]
members = [
    "rs/canister/api",
    "rs/canister/impl",
    "rs/consumer",
    "rs/consumer/agent_runtime",
    "rs/consumer/cdk_runtime",
    "rs/producer",
    "rs/producer/agent_runtime",
    "rs/producer/cdk_runtime",
    "rs/integration_tests",
    "rs/utils",
]
resolver = "2"

[workspace.dependencies]
candid = "0.10.3"
ic-agent = "0.33.0"
ic-cdk = "0.12.0"
ic-cdk-timers = "0.6.0"
ic-http-certification = "2.5.0"
ic_principal = "0.1.1"
ic-stable-structures = "0.6.3"
pocket-ic = "2.1.0"
rand = "0.8.5"
rmp-serde = "1.1.2"
serde = "1.0.196"
serde_bytes = "0.11.14"
serde_json = "1.0.114"
sha2 = "0.10.8"
test-case = "3.3.1"
time = "0.3.36"
tokio = "1.36.0"
tokio-util = "0.7.10"
tracing = "0.1.40"
